### ISSUE TITLE
Dev loop fails before a build

### ISSUE THREAD

**Issue by spericas** [oracle/helidon-build-tools#114]
Version: 2.0.0-M3
Steps to reproduce

```
>> helidon init --version 2.0.0-M2 --flavor mp
Creating helidon-quickstart-mp using version 2.0.0-M2
Switch directory to ./helidon-quickstart-mp to use CLI

>> cd ...; helidon dev

| building (full)
| build completed (1.8 seconds)
| helidon-quickstart-mp starting

Exception in thread "main" java.lang.NoClassDefFoundError: io/helidon/microprofile/server/Server
        at io.helidon.examples.quickstart.mp.Main.startServer(Main.java:59)
        at io.helidon.examples.quickstart.mp.Main.main(Main.java:46)
Caused by: java.lang.ClassNotFoundException: io.helidon.microprofile.server.Server
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 2 more

```

**Comment by rups10** [comment]
I am facing same issue again..
version : 2.3.0 

D:\git\code\card-systems\card-core\card-corporate-service-core\target>java -jar card-corporate-service-core-3.0.jar
CardCorporateServiceMain - main() started ========
Exception in thread "main" java.lang.NoClassDefFoundError: io/helidon/microprofile/server/Server
        at jp.co.rakuten_card.service.realtime.corporate.main.CardCorporateServiceMain.startServer(CardCorporateServiceMain.java:33)
        at jp.co.rakuten_card.service.realtime.corporate.main.CardCorporateServiceMain.main(CardCorporateServiceMain.java:28)
Caused by: java.lang.ClassNotFoundException: io.helidon.microprofile.server.Server
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 2 more

**Comment by romain-grecourt** [comment]
@rups10 You are launching the JVM manually here, it does not related to the CLI or any of the build tools sub-projects.

The class-path is generated at build time in the manifest of your application JAR file, it references the JAR files under the co-located `lib` folder. I suggest you check the files under `lib`, especially `helidon-microprofile-server-2.3.0.jar`
