### ISSUE TITLE
helidon init throws NPE when offline

### ISSUE THREAD

**Issue by danielkec** [oracle/helidon-build-tools#167]
```sh
kec@vulcan:~/idp/playground/vignette-register$ helidon init 
Looking up latest Helidon version
Helidon version: 
Helidon flavor
  (1) SE 
  (2) MP 
Enter selection (Default: 1): 2
Exception in thread "main" java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.util.regex.Matcher.reset(Matcher.java:416)
	at java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.util.regex.Pattern.matcher(Pattern.java:1133)
	at java.util.Formatter.parse(Formatter.java:2700)
	at java.util.Formatter.format(Formatter.java:2655)
	at java.util.Formatter.format(Formatter.java:2609)
	at java.lang.String.format(String.java:2897)
	at io.helidon.build.util.Style.render(Style.java:259)
	at io.helidon.build.util.SystemLogWriter.toStyled(SystemLogWriter.java:156)
	at io.helidon.build.util.SystemLogWriter.write(SystemLogWriter.java:129)
	at io.helidon.build.util.Log.log(Log.java:266)
	at io.helidon.build.cli.harness.CommandContext$ExitAction.exit(CommandContext.java:183)
	at io.helidon.build.cli.harness.CommandContext$ExitAction.lambda$run$1(CommandContext.java:162)
	at java.util.Optional.ifPresentOrElse(Optional.java:203)
	at io.helidon.build.cli.harness.CommandContext$ExitAction.run(CommandContext.java:156)
	at io.helidon.build.cli.harness.CommandRunner.execute(CommandRunner.java:123)
	at io.helidon.build.cli.impl.Main.main(Main.java:36)

```

**Comment by danielkec** [comment]
I would expect versions to be looked up from local repo in such case

**Comment by batsatt** [comment]
We debated supporting the local repo as a fallback, and chose not to. We can debate whether or not that is the right decision, but...

There is an actual bug here: we aren't checking the result of the prompt for the version, and simply hitting enter will result in this stack trace.

**Comment by danielkec** [comment]
Yeah sure, weird thing is it didn't resolved the latest version even after I have fixed the network issue

**Comment by danielkec** [comment]
If I get it right it wouldn't even ask for it if it did? 
```java
            if (helidonVersion == null) {
                helidonVersion = prompt("Helidon version", helidonVersion);
            }
```
