### ISSUE TITLE
CLI NPE on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by danielkec** [oracle/helidon-build-tools#176]
Same binary works ok on my Ubuntu 18.4.4 LTS but fails on Ubuntu 20.04 LTS,
CLI bin version: 2.0.0-RC1, master(11.6.2020)
```
kec@ubukec:~/idp/playground$ cp ~/helidon /usr/bin/helidon
kec@ubukec:~/idp/playground$ sudo chmod 777 /usr/bin/helidon
kec@ubukec:~/idp/playground$ helidon init
Exception in thread "main" java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.util.regex.Matcher.reset(Matcher.java:416)
	at java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.util.regex.Pattern.matcher(Pattern.java:1133)
	at java.util.Formatter.parse(Formatter.java:2700)
	at java.util.Formatter.format(Formatter.java:2655)
	at java.util.Formatter.format(Formatter.java:2609)
	at java.lang.String.format(String.java:2897)
	at io.helidon.build.util.Style.render(Style.java:259)
	at io.helidon.build.util.SystemLogWriter.toStyled(SystemLogWriter.java:156)
	at io.helidon.build.util.SystemLogWriter.write(SystemLogWriter.java:129)
	at io.helidon.build.util.Log.log(Log.java:266)
	at io.helidon.build.cli.harness.CommandContext$ExitAction.exit(CommandContext.java:183)
	at io.helidon.build.cli.harness.CommandContext$ExitAction.lambda$run$1(CommandContext.java:162)
	at java.util.Optional.ifPresentOrElse(Optional.java:203)
	at io.helidon.build.cli.harness.CommandContext$ExitAction.run(CommandContext.java:156)
	at io.helidon.build.cli.harness.CommandRunner.execute(CommandRunner.java:123)
	at io.helidon.build.cli.impl.Main.main(Main.java:36)
kec@ubukec:~/idp/playground$ cd myproject/
kec@ubukec:~/idp/playground/myproject$ helidon build
Exception in thread "main" java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.util.regex.Matcher.reset(Matcher.java:416)
	at java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.util.regex.Pattern.matcher(Pattern.java:1133)
	at java.util.Formatter.parse(Formatter.java:2700)
	at java.util.Formatter.format(Formatter.java:2655)
	at java.util.Formatter.format(Formatter.java:2609)
	at java.lang.String.format(String.java:2897)
	at io.helidon.build.util.Style.render(Style.java:259)
	at io.helidon.build.util.SystemLogWriter.toStyled(SystemLogWriter.java:156)
	at io.helidon.build.util.SystemLogWriter.write(SystemLogWriter.java:129)
	at io.helidon.build.util.Log.log(Log.java:266)
	at io.helidon.build.cli.harness.CommandContext$ExitAction.exit(CommandContext.java:183)
	at io.helidon.build.cli.harness.CommandContext$ExitAction.lambda$run$1(CommandContext.java:162)
	at java.util.Optional.ifPresentOrElse(Optional.java:203)
	at io.helidon.build.cli.harness.CommandContext$ExitAction.run(CommandContext.java:156)
	at io.helidon.build.cli.harness.CommandRunner.execute(CommandRunner.java:123)
	at io.helidon.build.cli.impl.Main.main(Main.java:36)

```

**Comment by m0mus** [comment]
The same thing happens on MacOS.

**Comment by m0mus** [comment]
It's been caused by:
1. `JAVA_HOME` environment variable was not set. CLI must clearly indicate it instead of failing with an exception.
2. Maven was installed using `brew` and `MAVEN_HOME` environment variable is not set. In this case CLI cannot properly detect Maven `lib` directory. It's hidden inside `libexec` directory, it's `brew` specific. It would be nice to support this scenario because many Mac users are using `brew`. As minimum CLI should request creating `MAVEN_HOME` environment variable.

**Comment by danielkec** [comment]
When I have printed out the Exception returning `null` as `getMessage`
```
kec@ubukec:~/idp/helidon-build-tools/helidon-cli/impl/target$ ./helidon init
java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
	at java.lang.Class.ensureInitialized(DynamicHub.java:499)
	at io.helidon.build.util.MavenCommand.mavenExecutable(MavenCommand.java:107)
	at io.helidon.build.util.MavenCommand.mavenHome(MavenCommand.java:129)
	at io.helidon.build.util.MavenCommand.installedVersion(MavenCommand.java:142)
	at io.helidon.build.util.MavenCommand.assertRequiredMavenVersion(MavenCommand.java:163)
	at io.helidon.build.cli.impl.CommandRequirements.requireMinimumMavenVersion(CommandRequirements.java:77)
	at io.helidon.build.cli.impl.InitCommand.execute(InitCommand.java:145)
	at io.helidon.build.cli.harness.CommandRunner.doExecuteCommand(CommandRunner.java:76)
	at java.util.Optional.ifPresentOrElse(Optional.java:201)
	at io.helidon.build.cli.harness.CommandRunner.doExecuteCommandName(CommandRunner.java:59)
	at java.util.Optional.ifPresentOrElse(Optional.java:201)
	at io.helidon.build.cli.harness.CommandRunner.doExecute(CommandRunner.java:49)
	at java.util.Optional.ifPresentOrElse(Optional.java:203)
	at io.helidon.build.cli.harness.CommandRunner.execute(CommandRunner.java:42)
	at io.helidon.build.cli.harness.CommandRunner.execute(CommandRunner.java:108)
	at io.helidon.build.cli.harness.CommandRunner.execute(CommandRunner.java:122)
	at io.helidon.build.cli.impl.Main.main(Main.java:36)
Caused by: java.lang.RuntimeException: Unable to find Java installation, please set JAVA_HOME
	at io.helidon.build.util.Constants.javaHome(Constants.java:64)
	at io.helidon.build.util.FileUtils.<clinit>(FileUtils.java:51)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	... 17 more
kec@ubukec:~/idp/helidon-build-tools/helidon-cli/impl/target$ whereis java
java: /usr/bin/java /usr/share/java /usr/lib/jvm/graalvm-ce-java11-20.1.0/bin/java /usr/share/man/man1/java.1.gz
kec@ubukec:~/idp/helidon-build-tools/helidon-cli/impl/target$ ll -la /usr/bin/java
lrwxrwxrwx 1 root root 22 kvě  4 13:12 /usr/bin/java -> /etc/alternatives/java*
```

**Comment by spericas** [comment]
At first glance, looks like a general problem related to how messages are styled and logged. `CommandContext` can call `Log.log(level, error, message)` with either `message` or `error` as `null`, but the implementation of that method seems to assume both params to be non-null.
