### ISSUE TITLE
--plain does not work

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon-build-tools#314]
```
helidon version --plain
Exception in thread "main" java.lang.IllegalStateException: Color support is already enabled
	at io.helidon.build.util.AnsiConsoleInstaller.disable(AnsiConsoleInstaller.java:92)
	at io.helidon.build.cli.harness.CommandRunner.doExecuteCommand(CommandRunner.java:73)
	at java.util.Optional.ifPresentOrElse(Optional.java:201)
	at io.helidon.build.cli.harness.CommandRunner.doExecuteCommandName(CommandRunner.java:62)
	at java.util.Optional.ifPresentOrElse(Optional.java:201)
	at io.helidon.build.cli.harness.CommandRunner.doExecute(CommandRunner.java:52)
	at java.util.Optional.ifPresentOrElse(Optional.java:203)
	at io.helidon.build.cli.harness.CommandRunner.execute(CommandRunner.java:45)
	at io.helidon.build.cli.harness.CommandRunner.execute(CommandRunner.java:120)
	at io.helidon.build.cli.harness.CommandRunner.execute(CommandRunner.java:134)
	at io.helidon.build.cli.impl.Main.main(Main.java:36)
```

**Comment by batsatt** [comment]
@romain-grecourt This works fine for me; what version are you using, and is it native?

**Comment by romain-grecourt** [comment]
Turns out this was cause by the use of proxy.
