### ISSUE TITLE
Jlink-image error on OpenJDK

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon-build-tools#321]
## Environment Details
* Helidon Version: 2.1.0
* Helidon MP
* JDK version: OpenJDK 11.0.8
* OS: Ubuntu 20.04 (running on Windows 10)
----------

`mvn package -Pjlink-image` fails with the following error:

```
---------------------------------------------------
Exception in thread "main" java.lang.Error: JRI creation failed.
        at io.helidon.linker.Linker.buildJri(Linker.java:198)
        at io.helidon.linker.Linker.link(Linker.java:120)
        at io.helidon.build.maven.link.JLinkImageMojo.execute(JLinkImageMojo.java:139)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
➜  quickstart-mp java --version
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

**Comment by batsatt** [comment]
This stack trace suggests a problem with the OpenJDK build itself:

```
java.lang.module.FindException: Hash of java.rmi (78f13d32367200b0122ba757c24ce026b7392bb0286e8ab5bcb9c568a56ae684) differs to expected hash (7e93a2e59758d391d70f813dc4ea32c5faaa86aa632534ce38801c1b9a1a9874) recorded in java.base
             at java.base/java.lang.module.Resolver.findFail(Resolver.java:877)
  ```

This error has been reported on a more recent JDK version: https://bugs.launchpad.net/ubuntu/+source/openjdk-14/+bug/1868699

**Comment by batsatt** [comment]
This is almost certainly an OpenJDK build issue:

```
java.lang.module.FindException: Hash of java.rmi (78f13d32367200b0122ba757c24ce026b7392bb0286e8ab5bcb9c568a56ae684) differs to expected hash (7e93a2e59758d391d70f813dc4ea32c5faaa86aa632534ce38801c1b9a1a9874) recorded in java.base
         at java.base/java.lang.module.Resolver.findFail(Resolver.java:877)
```
There are a number of reports of this same or very similar error. 

@m0mus Please try the following command in this environment, I expect it will fail:
```
jlink --module-path . --add-modules java.rmi --output jri --verbose
```

**Comment by batsatt** [comment]
@m0mus Should I close this?

**Comment by m0mus** [comment]
Yes, I'll close it.
