### ISSUE TITLE
Latest helidon version(2.2.2) not found

### ISSUE THREAD

**Issue by danielkec** [oracle/helidon-build-tools#374]
```sh
kec@vulcan:~/tmp/jersey$ helidon version
build.date      2020-06-15 19:33:28 CEST
build.version   2.0.0-SNAPSHOT
build.revision  6808cc6a
kec@vulcan:~/tmp/jersey$ helidon init
Looking up latest Helidon version
Using Helidon version 2.2.2
Helidon flavor
  (1) SE 
  (2) MP 
Enter selection (Default: 1): 2
Gathering archetypes ... 
warning: Unable to download helidon-archetype-catalog-2.2.2.xml from https://repo.maven.apache.org/maven2
Helidon version 2.2.2 not found.

```

**Comment by danielkec** [comment]
```
kec@vulcan:~/tmp/jersey$ uname -v
#78~18.04.1-Ubuntu SMP Sat Mar 20 14:10:07 UTC 2021
kec@vulcan:~/tmp/jersey$ java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
kec@vulcan:~/tmp/jersey$ mvn -v
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /opt/maven
Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: /home/kec/.sdkman/candidates/java/11.0.10.hs-adpt
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-70-generic", arch: "amd64", family: "unix"

```

**Comment by romain-grecourt** [comment]
Can you use `--debug` and share the output ? You can also try `--reset`.

**Comment by danielkec** [comment]
Sure 
```
kec@vulcan:~/tmp/test$ helidon init --debug
Looking up latest Helidon version
attempting to open https://repo.maven.apache.org/maven2/io/helidon/helidon-project/maven-metadata.xml
opened https://repo.maven.apache.org/maven2/io/helidon/helidon-project/maven-metadata.xml
Latest Helidon version found: 2.2.2
Using Helidon version 2.2.2
Helidon flavor
  (1) SE 
  (2) MP 
Enter selection (Default: 1): 2
Gathering archetypes ... 
attempting to open https://repo.maven.apache.org/maven2/io/helidon/archetypes/helidon-archetype-catalog/2.2.2/helidon-archetype-catalog-2.2.2.xml
warning: Unable to download helidon-archetype-catalog-2.2.2.xml from https://repo.maven.apache.org/maven2
java.io.FileNotFoundException: https://repo.maven.apache.org/maven2/io/helidon/archetypes/helidon-archetype-catalog/2.2.2/helidon-archetype-catalog-2.2.2.xml
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1915)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at io.helidon.build.util.NetworkConnection.lambda$static$0(NetworkConnection.java:75)
	at io.helidon.build.util.NetworkConnection$Builder.open(NetworkConnection.java:263)
	at io.helidon.build.cli.impl.ArchetypeBrowser.open(ArchetypeBrowser.java:232)
	at io.helidon.build.cli.impl.ArchetypeBrowser.downloadArtifact(ArchetypeBrowser.java:212)
	at io.helidon.build.cli.impl.ArchetypeBrowser.downloadCatalog(ArchetypeBrowser.java:195)
	at io.helidon.build.cli.impl.ArchetypeBrowser.archetypes(ArchetypeBrowser.java:112)
	at io.helidon.build.cli.impl.InitCommand.execute(InitCommand.java:176)
	at io.helidon.build.cli.harness.CommandRunner.doExecuteCommand(CommandRunner.java:76)
	at java.util.Optional.ifPresentOrElse(Optional.java:201)
	at io.helidon.build.cli.harness.CommandRunner.doExecuteCommandName(CommandRunner.java:59)
	at java.util.Optional.ifPresentOrElse(Optional.java:201)
	at io.helidon.build.cli.harness.CommandRunner.doExecute(CommandRunner.java:49)
	at java.util.Optional.ifPresentOrElse(Optional.java:203)
	at io.helidon.build.cli.harness.CommandRunner.execute(CommandRunner.java:42)
	at io.helidon.build.cli.harness.CommandRunner.execute(CommandRunner.java:108)
	at io.helidon.build.cli.harness.CommandRunner.execute(CommandRunner.java:122)
	at io.helidon.build.cli.impl.Main.main(Main.java:36)

attempting to open file:/home/kec/.m2/repository/io/helidon/archetypes/helidon-archetype-catalog/2.2.2/helidon-archetype-catalog-2.2.2.xml
Unable to download helidon-archetype-catalog-2.2.2.xml from file:///home/kec/.m2/repository
java.io.FileNotFoundException: /home/kec/.m2/repository/io/helidon/archetypes/helidon-archetype-catalog/2.2.2/helidon-archetype-catalog-2.2.2.xml (No such file or directory)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_io_FileNotFoundException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
	at java.io.FileInputStream.open0(FileInputStream.java)
	at java.io.FileInputStream.open(FileInputStream.java:219)
	at java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.io.FileInputStream.<init>(FileInputStream.java:112)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
	at io.helidon.build.util.NetworkConnection.lambda$static$0(NetworkConnection.java:75)
	at io.helidon.build.util.NetworkConnection$Builder.open(NetworkConnection.java:263)
	at io.helidon.build.cli.impl.ArchetypeBrowser.open(ArchetypeBrowser.java:232)
	at io.helidon.build.cli.impl.ArchetypeBrowser.downloadArtifact(ArchetypeBrowser.java:212)
	at io.helidon.build.cli.impl.ArchetypeBrowser.downloadCatalog(ArchetypeBrowser.java:195)
	at io.helidon.build.cli.impl.ArchetypeBrowser.archetypes(ArchetypeBrowser.java:115)
	at io.helidon.build.cli.impl.InitCommand.execute(InitCommand.java:176)
	at io.helidon.build.cli.harness.CommandRunner.doExecuteCommand(CommandRunner.java:76)
	at java.util.Optional.ifPresentOrElse(Optional.java:201)
	at io.helidon.build.cli.harness.CommandRunner.doExecuteCommandName(CommandRunner.java:59)
	at java.util.Optional.ifPresentOrElse(Optional.java:201)
	at io.helidon.build.cli.harness.CommandRunner.doExecute(CommandRunner.java:49)
	at java.util.Optional.ifPresentOrElse(Optional.java:203)
	at io.helidon.build.cli.harness.CommandRunner.execute(CommandRunner.java:42)
	at io.helidon.build.cli.harness.CommandRunner.execute(CommandRunner.java:108)
	at io.helidon.build.cli.harness.CommandRunner.execute(CommandRunner.java:122)
	at io.helidon.build.cli.impl.Main.main(Main.java:36)


Helidon version 2.2.2 not found.
```

```
kec@vulcan:~/tmp/test$ wget https://repo.maven.apache.org/maven2/io/helidon/archetypes/helidon-archetype-catalog/2.2.2/helidon-archetype-catalog-2.2.2.xml
--2021-04-06 07:53:44--  https://repo.maven.apache.org/maven2/io/helidon/archetypes/helidon-archetype-catalog/2.2.2/helidon-archetype-catalog-2.2.2.xml
Resolving repo.maven.apache.org (repo.maven.apache.org)... 199.232.16.215
Connecting to repo.maven.apache.org (repo.maven.apache.org)|199.232.16.215|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-04-06 07:53:44 ERROR 404: Not Found.
```

**Comment by romain-grecourt** [comment]
Your cli is super outdated (it's one of the first snapshot builds). Can you download the latest and try again ?

**Comment by danielkec** [comment]
Sorry my bad 😬
